spring:
   application:
      name: CONFIG_SERVER
   cloud:
      config:
         server:
            git:
               uri: https://github.com/somnath46/jt-config-properties
server:
   port: 9196

# eureka client configuration
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         default-zone: http://localhost:8761/eureka
   instance: localhost   
